discovery.tcp.port = 47500
discovery.tcp.port.range = 0

discovery.tcp.reconnect = 10

discovery.tcp.network.timeout = 5000
discovery.tcp.socket.timeout = 2000
discovery.tcp.ack.timeout = 2000
discovery.tcp.join.timeout = 0

discovery.tcp.stat.printfreq = 0

communication.message.queue.limit = 1024
